# Конфигурация демона key-sender

# общие настройки
common:
    ifname: 'br0'
    ipaddr: '192.168.0.2'
    login: 'root'
    password: 'root'
    srcfile: '/home/alex-m/keys'
    dstdir: '/mnt/configs/'
	
#ping настройки
ping:
    timeout: 2	# с, время ожидания отклика
    count: 3	# шт, количество запросов

# ssh настройки
sshpass:
    timeout: 2	# с, время ожидания соединения

